import type { PublicCampaignListing } from "./types";
import {
  SAMPLE_TAMRA_YUKHAE_DETAIL,
  createDefaultPublicCampaignDetail,
} from "./detail";

/** MVP 기본 카탈로그 — Supabase·ERP 동기화 전 공개 포털 시드 */
export const DEFAULT_PUBLIC_CAMPAIGNS: PublicCampaignListing[] = [
  {
    id: "pub-sample-tamra",
    title: "[경기/수원시] 탐라육해 인계점",
    benefitSummary: "5만원 상당 식사권",
    channel: "instagram",
    deliveryType: "visit",
    regionLabel: "[경기/수원시]",
    applicationCount: 96,
    targetHeadcount: 1,
    deadlineAt: "2026-06-28T23:59:59.000Z",
    points: 250_000,
    isPremium: true,
    schedulingStatus: "recruiting",
    createdAt: "2026-06-15T09:00:00.000Z",
    detail: SAMPLE_TAMRA_YUKHAE_DETAIL,
  },
  {
    id: "pub-exc-c3-1",
    campaignId: "exc-c3-1",
    title: "[제주 흑돼지] 1차 체험단",
    benefitSummary: "2인 코스 제공 + 주차 지원",
    channel: "blog",
    deliveryType: "visit",
    regionLabel: "[제주/제주시]",
    applicationCount: 3,
    targetHeadcount: 10,
    deadlineAt: "2026-07-04T23:59:59.000Z",
    schedulingStatus: "recruiting",
    createdAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "pub-1",
    title: "[재택] 제주 흑돼지 맛집 2인 식사권",
    benefitSummary: "5만원 상당 코스 메뉴 + 주차 지원",
    channel: "blog",
    deliveryType: "delivery",
    regionLabel: "[재택]",
    applicationCount: 1240,
    targetHeadcount: 5,
    deadlineAt: "2026-06-28T23:59:59.000Z",
    isPremium: true,
    schedulingStatus: "recruiting",
    createdAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "pub-2",
    title: "[제주/제주시] 오션뷰 카페 브런치",
    benefitSummary: "2인 브런치 세트 + 음료",
    channel: "reels",
    deliveryType: "visit",
    regionLabel: "[제주/제주시]",
    applicationCount: 318,
    targetHeadcount: 3,
    deadlineAt: "2026-06-22T23:59:59.000Z",
    points: 120_000,
    schedulingStatus: "recruiting",
    createdAt: "2026-06-18T09:00:00.000Z",
  },
  {
    id: "pub-3",
    title: "[서울/마포구] 핸드드립 원두 체험 키트",
    benefitSummary: "200g 원두 + 드립툴 세트",
    channel: "instagram",
    deliveryType: "delivery",
    regionLabel: "[재택]",
    applicationCount: 892,
    targetHeadcount: 10,
    deadlineAt: "2026-06-21T23:59:59.000Z",
    schedulingStatus: "recruiting",
    createdAt: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "pub-4",
    title: "[부산/해운대] 스파 1회 이용권",
    benefitSummary: "아로마 60분 + 라운지 이용",
    channel: "youtube",
    deliveryType: "visit",
    regionLabel: "[부산/해운대]",
    applicationCount: 156,
    targetHeadcount: 2,
    deadlineAt: "2026-06-20T23:59:59.000Z",
    points: 80_000,
    schedulingStatus: "recruiting",
    createdAt: "2026-06-19T09:00:00.000Z",
  },
  {
    id: "pub-5",
    title: "[재택] 프리미엄 과일 박스",
    benefitSummary: "제철 과일 3~5만원 상당",
    channel: "blog",
    deliveryType: "delivery",
    regionLabel: "[재택]",
    applicationCount: 2100,
    targetHeadcount: 20,
    deadlineAt: "2026-06-25T23:59:59.000Z",
    schedulingStatus: "recruiting",
    createdAt: "2026-06-12T09:00:00.000Z",
  },
];

export const PUBLIC_PORTAL_STORAGE_KEY = "tripitkorea-public-portal-v1";

/** ERP → 공개 포털 카탈로그 동기화용 (JSON 파일·Supabase 전 단계) */
export const PUBLIC_CATALOG_EXPORT_KEY = "tripitkorea-public-catalog-export-v1";
